# Generated by Django 5.0.1 on 2024-04-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0003_usermessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
