# Generated by Django 5.0.1 on 2024-04-18 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0004_delete_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='receipt_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='message',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
