# Generated by Django 5.0.1 on 2024-04-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0005_rentalapplication_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
