# Generated by Django 5.0.1 on 2024-04-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0006_rentalapplication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ongoing',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address_line_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='address_line_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='post_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
