# Generated by Django 5.0.1 on 2024-04-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0007_property_ongoing_alter_property_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ongoing',
            field=models.CharField(default=True, max_length=5),
        ),
    ]
