# Generated by Django 5.0.1 on 2024-04-21 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0010_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_display',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
