# Generated by Django 5.0.1 on 2024-04-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0011_user_last_login_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_login',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
