# Generated by Django 5.0.1 on 2024-04-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0013_loginhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='previous_login',
            new_name='last_recorded_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_display',
        ),
    ]
