# Generated by Django 5.0.1 on 2024-04-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0014_rename_previous_login_user_last_recorded_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_recorded_login',
            new_name='last_logout_time',
        ),
    ]
