# Generated by Django 5.0.1 on 2024-04-21 20:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0015_rename_last_recorded_login_user_last_logout_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-login_time']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_logout_time',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_display',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
