# Generated by Django 5.0.1 on 2024-04-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0016_alter_loginhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_display',
        ),
        migrations.AddField(
            model_name='user',
            name='second_last_login',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
