# Generated by Django 5.0.1 on 2024-04-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthExample', '0017_remove_user_last_login_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='second_last_login',
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
    ]
